-- MySQL Script generated by MySQL Workbench
-- Thu Dec  1 11:28:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema move
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema move
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `move` DEFAULT CHARACTER SET utf8 ;
USE `move` ;

-- -----------------------------------------------------
-- Table `move`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `move`.`film` (
  `idfilm` INT NOT NULL AUTO_INCREMENT,
  `rodzaj` VARCHAR(45) NULL,
  `dlugosc` INT NULL,
  `rok_produkcji` INT NULL,
  `autor` VARCHAR(45) NULL,
  `nazwa` VARCHAR(45) NULL,
  `wypozyczony` VARCHAR(3) NULL,
  PRIMARY KEY (`idfilm`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `move`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `move`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `move`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `move`.`admin` (
  `idadmin` INT NOT NULL,
  `login` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idadmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `move`.`dostepne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `move`.`dostepne` (
  `iddostep` INT NOT NULL,
  `film_idfilm` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  `admin_idadmin` INT NOT NULL,
  PRIMARY KEY (`iddostep`, `film_idfilm`, `user_iduser`, `admin_idadmin`),
  CONSTRAINT `fk_dostep_film1`
    FOREIGN KEY (`film_idfilm`)
    REFERENCES `move`.`film` (`idfilm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dostepne_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `move`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dostepne_admin1`
    FOREIGN KEY (`admin_idadmin`)
    REFERENCES `move`.`admin` (`idadmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
